apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-ff5bd4f3-288a-45ab-bd56-1e7ccc50b29a 
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-829c1fa4-7e2a-4aa8-99ed-c2398269e783 
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: default  # namespace where the pvc's exist
  name: volume-migration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: ubuntu:xenial
          tty: true
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -r -v /mnt/old/* /mnt/new" ]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          persistentVolumeClaim:
            claimName: old-pvc # change to data source pvc
        - name: new-vol
          persistentVolumeClaim:
            claimName: new-pvc # ch
