apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-tls-certificate
  namespace: cert-manager
spec:
  secretName: my-app-tls-secret
  dnsNames:
    - homeassistant.home.local
  issuerRef:
    name: tls-ca-issuer
    kind: ClusterIssuer
