---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
    # - role: mqttreporter
- hosts: master
  become: yes
  roles:
    - role: k3s/master
# - hosts: nodes
#   become: yes
#   roles:
#     - role: k3s/node
