---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Europe/London"
      UMASK: "022"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        mountPath: /media
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.0.13"
            path: "/volume2/Media"
    podSecurityContext:
      runAsUser: 1026
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "Always"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/issuer: "letsencrypt-prod"
        hosts:
          - host: radarr.local
            paths:
              - path: /
          - host: radarr.picluster.nickbabenko.com
            paths:
              - path: /
        tls:
          - secretName: radarr-ingress-tls
            hosts:
              - radarr.picluster.nickbabenko.com
    resources:
      limits:
        cpu: 750m
        memory: 1024Mi
    requests:
      cpu: 750m
      memory: 1024Mi

