---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus 
      version: 15.10.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alertmanager:
      persistentVolume:
        storageClass: longhorn
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /
        annotations:
          cert-manager.io/issuer: "letsencrypt-prod"
        hosts:
          - prometheus.local
          - prometheus.nickbabenko.com
        tls:
          - secretName: ingress-tls-prometheus
      persistentVolume:
        storageClass: longhorn
    pushgateway:
      enabled: false
