---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: home
spec:
  chart:
    spec:
      chart: openfaas
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  interval: 1m0s
  targetNamespace: home
  values:
    basic_auth: false
    operator:
      create: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas-mqtt
  namespace: home
spec:
  chart:
    spec:
      chart: mqtt-connector
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  interval: 1m0s
  targetNamespace: home
  values:
    basic_auth: false
    broker: tcp://mosquitto:1883
    topic: zigbee2mqtt
    gateway_url: http://gateway:8080
