---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqtt-exporter
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: mqtt-exporter
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: samipsolutions
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      MQTT_ADDRESS: mosquitto
