---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Europe/London"
    image:
      tag: "2023.1"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 4Gi
        mountPath: /config
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: esphome.local
            paths:
              - path: /
