---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/cloudflare/argo-tunnel-examples.git
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/cloudflare-tunnel
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: cloudflare-tunnel
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: erisamoe/cloudflared
      tag: 2022.9.1
    warp-routing:
      enabled: true
    cloudflare:
      ingress:
        - hostname: radarr.picluster.nickbabenko.com
          service: http://radarr.media.svc.cluster.local
        - hostname: sonarr.picluster.nickbabenko.com
          service: https://nginx-ingress-ingress-nginx-controller.networking.svc.cluster.local:443
  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-secret-values
      valuesKey: values.yaml
