---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/cloudflare/argo-tunnel-examples.git
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/cloudflare-tunnel
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: cloudflare-tunnel
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: erisamoe/cloudflared
      tag: 2022.9.1
    cloudflare:
      enableWarp: true
      ingress:
        - hostname: radarr.nickbabenko.com
          service: http://radarr.media.svc.cluster.local:7878
        - hostname: sonarr.nickbabenko.com
          service: http://sonarr.media.svc.cluster.local:8989
        - hostname: grafana.nickbabenko.com
          service: http://prometheus-grafana.monitoring.svc.cluster.local
        - hostname: ha.nickbabenko.com
          service: http://homeassistant-home-assistant.home.svc.cluster.local:8123
        - hostname: tele.nickbabenko.com
          service: https://teleport.networking.svc.cluster.local:443
        - hostname: code.nickbabenko.com
          service: http://codeserver-code-server.home.svc.cluster.local:8443
        - hostname: z2m.nickbabenko.com
          service: http://zigbee2mqtt.home.svc.cluster.local:8080
        - hostname: esphome.nickbabenko.com
          service: http://esphome.home.svc.cluster.local:6052
  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-secret-values
      valuesKey: values.yaml
