apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Europe/London"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: mqtt.local
            paths:
              - path: /
    service:
      main:
        type: NodePort
        ports:
          mqtt:
            nodePort: 30000
