---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clusterName: homeserv
    acme: true
    persistence:
      existingClaimName: teleport-pvc
  valuesFrom:
    - kind: Secret
      name: teleport-secret-values
      valuesKey: values.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: foo-pv
