---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clusterName: tele.nickbabenko.com
    acme: true
    persistence:
      existingClaimName: teleport-pvc
    service:
      kind: ClusterIP
    proxyListenerMode: multiplex
  valuesFrom:
    - kind: Secret
      name: teleport-secret-values
      valuesKey: values.yaml
