apiVersion: v1
stringData:
    values.yaml: ENC[AES256_GCM,data:3bnSoSwEnMpVPJtwd0+AC1XpAMDJhXGEgcEWePeQ,iv:d6+1o4RuZ+6I1wFwozImKdnhvOV26Namv0TyAaVUUcY=,tag:XQNtpbVL7CDXMPpqolU8Fg==,type:str]
kind: Secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-14T23:33:28Z"
    mac: ENC[AES256_GCM,data:gpxpnDtd2LLSvVNLRNpT9oYekfxCgvCWOce5tZOq9UOtI/dU4gSJ/nxt5+WTaDCle1pCVSBK3CcKo9Id1gLCoQQyOAE5Zwv2cnpQKS5opCdA4mE3RDhVO7IA3jhwcsmm3rM7j96WwAl/sOHpv9QVhV5UCLqtQY+Lpix6DBn8atI=,iv:neoWe7G+slsZIavgFBE3Qy/CBWsoBvAV6xXCzPfSK14=,tag:V+1B6/BiEU2JriuUBtzbng==,type:str]
    pgp:
        - created_at: "2023-01-14T23:33:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+HDEsMntAdvARAApKjIIpn9sRE4GNdp3ovThCEBt3NRofMPF9mgr+iyyyPR
            awp76tu9MVcPoR8OPWgChCPvgDEeBtO3tjNY/DMbvMg4Cc4KGQ4Np+DS9TC5IN0v
            g8FHf2eEG58MnEQue8SNzvXNTtd7TrV9eJZl+SPvFbYxtckbKC6HFW3nutOhLuuc
            WHQ/sgBySYCnmKMgTEdDbGHkYy6aG5bf1+NkZJsi99KOT42HRR390gKjzeRzpyeS
            w3i9A6NLKNkU1WfTvquQyE227R2nkNzZFCCgetXd0T1vse2rHb2Ex/Zb9FnE01qT
            Tub6/Ykl+nUAQ4Jn0hxK2u3M2hUx0pt5M3pQiKbOcPxtHvfoPErcBiOmuUyV3Dor
            j68Yh2MhKWZbzbWVnlxeIlG6INcuzGBQrY8C1kAVpJEf3PmzpIkW5zKZivfOJcmq
            8BLp7n425UrSWukTIOjBKKPvp4HnCdhrM2DGTJK0UixQneUup9Iopi3KOZQdS2AD
            8v4vg8dRgUZFQzF8Bqdbnxq5dupIcydEOkE8QI5cuDfkpyiYdXa0MTZAVdxMxagN
            jMhf/p9d4ZovBpOO/holcvqz1n6cx/iKgcWIBSUOwa+zOW2LtuArg2NbYWroliZh
            mGtEZr2k9ACyXHPh74y0o6QGbTRO+QJOS2UNqlSaTuGUevRMntfa97RQD2g0uzPU
            ZgEJAhDxRiqtioNLmxv9maH+60nbLq1ULe/bw40rv+68XSJNehLsIjZdCPliCzrx
            Es0B2MkKy+B09lL9/7yL4s6A08kmQRKTIJ0Bf6Be1u42nnfkyA/A71MGyEnhVO/S
            WewoBHKNng==
            =7rPU
            -----END PGP MESSAGE-----
          fp: 9C1A0A83FC16142EE8427D9725999EF24B158490
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
