---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: homebridge
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Europe/London"
      PGID: 0
      PUID: 0
    persistence:
      # config:
      #   enabled: true
      #   mountPath: /homebridge
      #   accessMode: ReadWriteOnce
      #   size: 1Gi
      #   storageClass: longhorn
      static-config:
        enabled: true
        mountPath: /homebridge/config.json
        subPath: config.json
        type: secret
        name: homebridge-secret-values
      static-package:
        enabled: true
        mountPath: /homebridge/package.json
        subPath: package.json
        type: configMap
        name: homebridge-package
    hostNetwork: true
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: homebridge
          cert-manager.io/issuer: "letsencrypt-prod"
        ingressClassName: nginx
        hosts:
          - host: homebridge.local
            paths:
              - path: /
    podSecurityContext:
      fsGroup: 0
    configmap:
      scripts:
        enabled: true
        data:
          startup.sh: |
            npm install homebridge-google-nest-sdm homebridge-mqttthing homebridge-ring homebridge-securitysystem homebridge-z2mhomebridge_config
      package:
        enabled: true
        data:
          package.json: |
            {
              "private": true,
              "dependencies": {
                "homebridge-google-nest-sdm": "1.1.4",
                "homebridge-mqttthing": "1.1.42",
                "homebridge-ring": "11.3.0",
                "homebridge-securitysystem": "6.5.2",
                "homebridge-z2m": "1.9.2"
              }
            }
