---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pi-cluster
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/nickbabenko/pi-cluster-ansible

