---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflare-access-grafana
  name: cloudflare-access-grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-access-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudflare-access-grafana
    spec:
      containers:
        - image: "{{ .Value.image.name }}:{{ .Value.image.tag }}"
          name: cloudflare-access-grafana
          ports:
            - containerPort: {{.Value.deployment.port}}
          env:
            - name: AUTHDOMAIN
              value: https://<your-own-domain>.cloudflareaccess.com
            - name: POLICYAUD
              value: <YOUR_POLICY_AUD_TOKEN>
            - name: FORWARDHEADER
              value: X-WEBAUTH-USER
            - name: FORWARDHOST
              value: <grafana-host>:3000
            - name: ADDR
              value: :3001
      restartPolicy: Always
