---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflare-access-grafana
  name: cloudflare-access-grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-access-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudflare-access-grafana
    spec:
      containers:
        - image: "{{ .Value.image.name }}:{{ .Value.image.tag }}"
          name: cloudflare-access-grafana
          ports:
            - containerPort: {{.Value.deployment.port}}
          env:
            - name: AUTHDOMAIN
              value: {{.Values.auth_domain}}
            - name: POLICYAUD
              value: {{.Values.policy_aud}}
            - name: FORWARDHEADER
              value: {{.Values.forward_header}}
            - name: FORWARDHOST
              value: {{.Values.forward_host}}
            - name: ADDR
              value: {{.Values.config.address}}
      restartPolicy: Always
