---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudflare-access-grafana
  name: cloudflare-access-grafana
spec:
  ports:
    - name: 3001
      port: 3001
      targetPort: 3001
  selector:
    app: cloudflare-access-grafana
