---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudflare-access-grafana
  name: cloudflare-access-grafana
spec:
  ports:
    - name: http
      port: {{.Values.service.port}}
      targetPort: {{.Values.deployment.port}}
  selector:
    app: cloudflare-access-grafana
