apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-hosts
data: |
  192.168.0.21 home-assistant.local 
  192.168.0.22 home-assistant.local
  192.168.0.23 home-assistant.local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-conf
data: |
  user=root
  port=53
  bind-interfaces
  log-queries
