apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: networking
spec:
  type: NodePort
  ports:
    - port: 53
      name: dns
      protocol: UDP
      targetPort: 53
  selector:
    app: dnsmasq
