---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  chart:
    spec:
      chart: node-red
      sourceRef:
        kind: HelmRepository
        name: node-red
        namespace: flux-system
  interval: 1m0s
  targetNamespace: home
  values:
    persistence:
      enabled: true
      storageClass: longhorn
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: node-red.local
          paths:
            - path: /
              pathType: ImplementationSpecific
