---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      HA_URL: http://homeassistant-home-assistant.home.svc.cluster.local:8123
      DASH_URL: "http://$HOSTNAME:5050"
    image:
      tag: "4.2.1"
    envFrom:
      - secretRef:
          name: appdaemon-secret-values
    metrics:
      enabled: true
      serviceMonitor:
        labels:
          monitor: prometheus
