apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-tls-certificate
  namespace: home
spec:
  secretName: homeassistant-tls-secret
  dnsNames:
    - homeassistant.home.local
    - homeassistant.local
  issuerRef:
    name: tls-ca-issuer
    kind: ClusterIssuer
