---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      TZ: "Europe/London"
    image:
      tag: "2023.1"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 4Gi
        mountPath: /config
        accessMode: ReadWriteOnce
    mariadb:
      enabled: false
    metrics:
      enabled: true
    prometheusRule:
      enabled: true
      rules:
        - alert: HomeAssistantAbsent
          annotations:
            description: Home Assistant has disappeared from Prometheus service discovery.
            summary: Home Assistant is down.
          expr: |
            absent(up{job=~".*home-assistant.*"} == 1)
          for: 5m
          labels:
            severity: critical
    addons:
      codeserver:
        enabled: false
        args:
          - --auth
          - none
          - --user-data-dir
          - /data/config/.vscode
        volumeMounts:
          - name: config
            mountPath: /config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/issuer: "tls-ca-issuer"
        hosts:
          - host: homeassistant.local
            paths:
              - path: /
        tls:
          - secretName: homeassistant-ingress-tls
            hosts:
              - homeassistant.local
